### ISSUE TITLE
Koja je osnovna namjena aplikacije?

### ISSUE THREAD

**Issue by sbuljat** [jsoric/jsoric_zavrsni.github.io#4]
Malo je nejasno koja je namjena aplikacije, iz naziva i opisa u README očekivao sam da ću moći sam uređivati blog postove nakon što se registriram. Ovdje su blog postovi zapisani u flaskblog.py datoteci umjesto u bazi podataka.

**Comment by sbuljat** [comment]
Gdje je odgovor? Svaki otvoreni "Issue" bi trebao zatvoriti onaj tko ga je otvorio..

**Comment by jsoric** [comment]
Osnovna namjena je prikazana na ažuriranom Readme.md file-u, uz promjene na home stranici.

**Comment by sbuljat** [comment]
Bilo bi puno korisnije kad bi kao korisnik mogao odabrati putovanje i kupiti ga direktno preko stranice. Dio oko plaćanja se mogao ignorirati, ali cijeli proces se mogao izdefinirati.
